- name:     Initialize VIm shell command line
  set_fact: vimCommand='vim'
  when:     config.commands[0] is defined

- name:       Add the commands to the command line...
  set_fact:   vimCommand={{ vimCommand +' -c "'+ item +'"' }}
  with_items: "{{ config.commands | union([ 'qa!' ]) }}"
  when:       config.commands[0] is defined

- name:    Execute VIm commands by the command line
  command: "{{ vimCommand }}"
  when:    config.commands[0] is defined

