- name: Enable non free packages
  replace:
    dest:    /etc/apt/sources.list
    backup:  yes
    regexp:  '^(^(?:deb|deb-src)\s+.*main$)\s*$'
    replace: '\1 non-free'
  when:     tasks['utils']['config']['allow_non_free_packages']
  register: non_free
  become:   yes

- name: Initialize lists of required repositories and packages
  set_fact:
    repositories: []
    packages:     []

- name: Collecting the lists...
  set_fact:
    packages:     "{{ packages     | union(tasks[item].packages     | default([])) }}"
    repositories: "{{ repositories | union(tasks[item].repositories | default([])) }}"
  with_items: "{{ tasks | list }}"

- name: Repositories installation...
  include: repository-add.yml
  with_items: "{{ repositories }}"

- name:       Refresh APT cache and upgrade current installed packages
  apt:        update_cache=yes upgrade=yes
  when:       (apt_repositories is defined and apt_repositories.changed) or non_free.changed
  become:     yes

- name:       Install new packages
  apt:        name={{ item }}
  with_items: "{{ packages }}"
  become:     yes

- name:     Check if VIm is already configured
  stat:     path='{{ ansible_env.HOME }}/.vim/bundle/vim-tweaks'
  register: customVim

- name:    VIm configurations...
  include: vim-configure.yml
  when:    customVim.stat.isdir is not defined or customVim.stat.isdir == False

- name: Remove message of the day
  file: path='{{ ansible_env.HOME }}/.hushlogin' state=touch

