- name:     Check if PHP is already configured
  stat:     path="{{ configuration.php.phpini }}"
  register: phpConfig

- name:     Configure PHP
  copy:     src={{ configuration.templates['php.ini'] }} dest="{{ configuration.php.phpini }}" owner=root group=root mode=0644
  when:     not phpConfig.stat.exists
  register: updateConfig

- name:    Reload php-fpm service
  service: name={{ configuration.php.phpService }} state=reloaded
  when:    updateConfig.changed

