- name:           Install repository {{ item.src }}
  apt_repository: repo={{ item.src }} mode=644 state=present
  register:       installRepo

- name:    Add apt key for repository {{ item.src }}
  apt_key: url={{ item.key }}
  when:    item.key is defined

