- hosts: all
  # Get the config
  vars_files:
    - vars/config.yml
  # Verify Ansible can run this playbook
  pre_tasks:
    - name: Check ansible version
      assert:
        that: "ansible_version.full | version_compare('2.2', '>=')"
        msg:  "You need to update Ansible!"
  # Include tasks to play when provisioning
  tasks:
    - name:    Include our tasks to the playbook
      include: tasks/{{ task }}/main.yml
      # Settings a different item name here because {{ item }} can be used in included files
      loop_control:
        loop_var: task
      # Beware: the order of this list is important...
      # For example, sites will depend on php, mysql, apache, ...
      with_items: [ 'utils', 'mysql', 'php', 'apache', 'sites' ]

