- hosts: all

  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full | version_compare('2.2', '>=')
        msg:  You need to update Ansible!
    # When cachier is enabled, you can define a list of dirs in vm.yml which will be re-assigned to vagrant user.
    # Useful for generic buckets because they can create folders as root. @see vm.yml for a better explanation.
    - name:       Fix ownerships of Vagrant cachier generic buckets...
      file:       path="{{ item }}" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"
      when:       configuration.vm.cachier.is_activated and configuration.vm.cachier.fixOwnership[0]
      with_items: "{{ configuration.vm.cachier.fixOwnership }}"
      become:     true

  roles:
    # Attach the main role to install the VM
    - webastien.dev-vm

