- name:     Check if Drush is already installed
  stat:     path="{{ config.binary }}"
  register: drush

- name:     Define the path where Drush will be downloaded
  set_fact: dlPath="{{ configuration.vm.dlFolder }}/drush"
  when:     not drush.stat.exists

- name:     Check if Drush has already been downloaded
  stat:     path="{{ dlPath }}"
  when:     not drush.stat.exists
  register: downloaded

- name: Create the target directory
  file: path="{{ dlPath }}" state=directory
  when: not drush.stat.exists and not downloaded.stat.exists

- name:  Install Drush in this directory
  shell: composer require "drush/drush" chdir="{{ dlPath }}"
  when:  not drush.stat.exists and not downloaded.stat.exists

# NOTE: Can't use Ansible module "copy" with "remote=true" because it doesn't support recursive
- name:   Copy Drush in the right place
  shell:  cp -r {{ dlPath }} {{ config.folder }}
  when:   not drush.stat.exists
  become: yes

- name:   Copy drush binary in the right place
  file:   src="{{ config.folder }}/vendor/drush/drush/drush" dest="{{ config.binary }}" state=link
  when:   not drush.stat.exists
  become: yes

- name:   Activate drush command's autocompletion
  file:   src="{{ config.folder }}/vendor/drush/drush/drush.complete.sh" dest=/etc/bash_completion.d/drush state=link
  when:   completion and not drush.stat.exists
  become: yes

- name:  Install Drush language commands for Drupal 7
  shell: drush dl --default-major=7 drush_language
  when:  config.language and not drush.stat.exists

